### ISSUE TITLE
How can i use the meta property of a column?

### ISSUE THREAD

**Issue by ferdiebergado** [jamesdordoy/vue-datatable#14]
I have a column which uses a component like this:

`        {
          label: "Action(s)",
          component: EditButton,
          classes: {
            btn: true,
            "btn-sm": true,
            "btn-primary": true
          },
          meta: {
            route: this.route
          },
          filterable: false
        }`

EditButton.vue

`<template>
  <a :class="classes" :href="editlink" role="button" title="Edit">
    <i class="far fa-edit"></i>
  </a>
</template>

<script>
export default {
  props: {
    data: {},
    classes: {},
    meta: {}
  },
  computed: {
    editlink: function() {
      return `${this.meta.route}/${this.data.id}/edit`;
    }
  }
};
</script>
`
But it says this.meta.route is undefined.

Am I using the meta prop correctly?

**Comment by d-lach** [comment]
I just experienced this issue as well,

the "meta" property of a column is not propagated to the data table cell in the current build. Here you can see that meta prop is missing in properly instantiated DataTableCell (checked via vue-debugger)
![image](https://user-images.githubusercontent.com/52693188/63345840-f6184b80-c353-11e9-88a6-72ca10456fd9.png)

In currently available `dist/laravel-vue-datatable-common.js` meta property is not present on **line 4615**

`var render = (...)` 

which I guess defines the render function of a cell.

So @ferdiebergado I think your code is correct. As a simple workaround, you can use `classes` property instead of `meta` to pass your column metadata to table cells :)  or manually import and compile sources from `node_modules/laravel_vue_datatable/src`.

**Comment by jamesdordoy** [comment]
Hey @ferdiebergado, apologies i didn't see your issue until now.

@d-lach Thanks for bringing this to my attention, i will get a new build published later tonight.

**Comment by jamesdordoy** [comment]
This should now be corrected in `0.3.4`

**Comment by denisbachtiar** [comment]
@jamesdordoy halo james, thank you for your vue datatable. its very helpful plugin for my laravel vue project. btw, i want to ask you something. can i put value from column data in meta props? 
i mean something like this:
meta: {data1: users.name, data2: users.phone}

you got it?
cause i will combine it in my component

**Comment by usmanfarooqch** [comment]
> @jamesdordoy halo james, thank you for your vue datatable. its very helpful plugin for my laravel vue project. btw, i want to ask you something. can i put value from column data in meta props?
> i mean something like this:
> meta: {data1: users.name, data2: users.phone}
> 
> you got it?
> cause i will combine it in my component

have you found any solution for this @denisbachtiar
